In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
data = np.random.rand(2,3,4)
# 2 - create 2 different arrays
# 3 - row count 
# 4 - column count
## use the differnt types of shapes

In [7]:
data

array([[[0.6652592 , 0.60672639, 0.68221594, 0.68720568],
        [0.80101144, 0.97204256, 0.26483979, 0.33941989],
        [0.05409215, 0.45521825, 0.59885871, 0.09428279]],

       [[0.85437764, 0.09519269, 0.03358816, 0.94943687],
        [0.9628424 , 0.08885538, 0.40747759, 0.63652205],
        [0.65542421, 0.88879404, 0.42977494, 0.52611248]]])

In [8]:
zeros = np.zeros((2,2,2)) #array fill only with the zeros
ones = np.ones((2,2,2)) #array filled only with the ones

In [9]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
full = np.full ((2,2,2),7) #create the array 

In [12]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [13]:
arr=np.array([[1,2,3],[4,5,6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
shape = data.shape
size = data.size
types = data.dtype

In [17]:
shape

(2, 3, 4)

In [18]:
size

24

In [19]:
types

dtype('float64')

In [20]:
data

array([[[0.6652592 , 0.60672639, 0.68221594, 0.68720568],
        [0.80101144, 0.97204256, 0.26483979, 0.33941989],
        [0.05409215, 0.45521825, 0.59885871, 0.09428279]],

       [[0.85437764, 0.09519269, 0.03358816, 0.94943687],
        [0.9628424 , 0.08885538, 0.40747759, 0.63652205],
        [0.65542421, 0.88879404, 0.42977494, 0.52611248]]])

In [21]:
arr = data[0] #access only the first array

In [22]:
arr

array([[0.6652592 , 0.60672639, 0.68221594, 0.68720568],
       [0.80101144, 0.97204256, 0.26483979, 0.33941989],
       [0.05409215, 0.45521825, 0.59885871, 0.09428279]])

In [24]:
arr = data[1] #access only the second array
arr

array([[0.85437764, 0.09519269, 0.03358816, 0.94943687],
       [0.9628424 , 0.08885538, 0.40747759, 0.63652205],
       [0.65542421, 0.88879404, 0.42977494, 0.52611248]])

In [25]:
arr = data [0][0] #oth array 0th row
arr

array([0.6652592 , 0.60672639, 0.68221594, 0.68720568])

In [26]:
arr = data [0][0][0:3] #oth array 0th row first 3 coloum
arr

array([0.6652592 , 0.60672639, 0.68221594])

In [33]:
arr=data[0][0:2]# 0th array, 0-2 range in the rows, all columns as no restrictions provided
arr

array([[0.6652592 , 0.60672639, 0.68221594, 0.68720568],
       [0.80101144, 0.97204256, 0.26483979, 0.33941989]])

In [29]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [30]:
list1

array([0.38242877, 0.71863503, 0.48121974, 0.35707597, 0.40662494,
       0.85652521, 0.06018076, 0.27547371, 0.16842763, 0.34608315])

In [31]:
list2

array([0.08988482, 0.4055989 , 0.305804  , 0.27145996, 0.74383041,
       0.98481876, 0.10665116, 0.17806938, 0.51979298, 0.450684  ])

In [34]:
add=np.add(list1,list2)

In [35]:
add

array([0.47231359, 1.12423393, 0.78702374, 0.62853592, 1.15045535,
       1.84134398, 0.16683192, 0.45354308, 0.68822062, 0.79676715])

In [36]:
subtract=np.subtract(list1,list2)

In [37]:
subtract

array([ 0.29254395,  0.31303613,  0.17541574,  0.08561601, -0.33720547,
       -0.12829355, -0.0464704 ,  0.09740433, -0.35136535, -0.10460086])

In [38]:
multiply=np.multiply(list1,list2)

In [39]:
multiply

array([0.03437454, 0.29147758, 0.14715892, 0.09693183, 0.30246   ,
       0.8435221 , 0.00641835, 0.04905343, 0.0875475 , 0.15597414])

In [40]:
divide=np.divide(list1,list2)

In [41]:
divide

array([4.25465365, 1.77178743, 1.57362146, 1.31539094, 0.54666351,
       0.86972877, 0.56427664, 1.54700213, 0.32402829, 0.76790644])

In [42]:
dot=np.dot(list1,list2) # multiply all values in the arrays at a strectch and derive one value. Important for distance calculations

In [43]:
dot

2.0149183795047616

In [44]:
minV=np.min(list2)

In [45]:
minV

0.08988481843571994

In [46]:
maxV=np.max(list2)

In [47]:
maxV

0.9848187641065944

In [48]:
sqrt=np.sqrt(25)
print(sqrt)

5.0


In [49]:
power=np.power(2,7)
power

128

In [50]:
absol=np.abs(-2)
absol

2

In [51]:
lg=np.log(5)
lg

1.6094379124341003

In [52]:
data[0][0][0]=700

In [53]:
data

array([[[7.00000000e+02, 6.06726386e-01, 6.82215941e-01, 6.87205676e-01],
        [8.01011440e-01, 9.72042556e-01, 2.64839793e-01, 3.39419886e-01],
        [5.40921537e-02, 4.55218248e-01, 5.98858709e-01, 9.42827883e-02]],

       [[8.54377636e-01, 9.51926887e-02, 3.35881566e-02, 9.49436866e-01],
        [9.62842404e-01, 8.88553788e-02, 4.07477592e-01, 6.36522049e-01],
        [6.55424207e-01, 8.88794045e-01, 4.29774942e-01, 5.26112477e-01]]])